reference: "reference/ref.fasta"

samples:
    SRR15006267: "raw_fastq/SRR15006267" # "raw_fastq/E_rothschildi.1.fq.gz"
    SRR15006269: "raw_fastq/SRR15006269" # "raw_fastq/E_rothschildi.2.fq.gz"

window: 10000000

params:
    bwa:
        bwa_threads: 30

    fastp:
        fastp_threads: 8

    hyplotype_caller:
        java_options: "--java-options \"-Xms512m -Xmx4g\""
    
    genotype_gvcfs:
        java_options: "--java-options \"-Xms512m -Xmx4g\""
    
    combine_vcf:
        java_options: "--java-options \"-Xms512m -Xmx4g\""    
    
    picard:
        picard_path: "/data/00/software/picard/picard.2.25.0.jar"